pub mod executor;

use super::expr::Expr;

// impl Visitor<Result<(), (&'static str, (usize, usize))>> for AstExecutor: run;
use executor::AstExecutor;

// trait: Stmt;

// type ExprStmt: expr: Box<dyn Expr>;
// type PrintStmt: expr: Box<dyn Expr>;

// autogenerated code

pub trait Stmt
{
	fn run(&self) -> Result<(), (&'static str, (usize, usize))>;
}

trait Visitor<I>
{
	fn visit_exprstmt(expr: &ExprStmt) -> I;
	fn visit_printstmt(expr: &PrintStmt) -> I;
}

pub struct ExprStmt
{
	pub expr: Box<dyn Expr>
}

impl Stmt for ExprStmt
{
	fn run(&self) -> Result<(), (&'static str, (usize, usize))>
	{ AstExecutor::visit_exprstmt(self) }
}

pub struct PrintStmt
{
	pub expr: Box<dyn Expr>
}

impl Stmt for PrintStmt
{
	fn run(&self) -> Result<(), (&'static str, (usize, usize))>
	{ AstExecutor::visit_printstmt(self) }
}
