pub mod executor;

// impl Visitor<Result<(), (&'static str, (usize, usize))>> for AstExecutor: run;
use executor::AstExecutor;

// trait: Stmt;

// autogenerated code

pub trait Stmt
{
	fn run(&self) -> Result<(), (&'static str, (usize, usize))>;
}

trait Visitor<I>
{
}
