pub mod executor;

use super::expr::Expr;

// impl Visitor<Result<(), (&'static str, (usize, usize))>> for VM: run;
use super::VM;

// trait: Stmt;

// type ExprStmt: expr: Box<dyn Expr>;
// type PrintStmt: expr: Box<dyn Expr>;
// type VarStmt: name: String, expr: Option<Box<dyn Expr>>;

// autogenerated code

pub trait Stmt
{
	fn run(&self, run: &mut VM) -> Result<(), (&'static str, (usize, usize))>;
}

trait Visitor<I>
{
	fn visit_exprstmt(&mut self, expr: &ExprStmt) -> I;
	fn visit_printstmt(&mut self, expr: &PrintStmt) -> I;
	fn visit_varstmt(&mut self, expr: &VarStmt) -> I;
}

pub struct ExprStmt
{
	pub expr: Box<dyn Expr>
}

impl Stmt for ExprStmt
{
	fn run(&self, run: &mut VM) -> Result<(), (&'static str, (usize, usize))>
	{ run.visit_exprstmt(self) }
}

pub struct PrintStmt
{
	pub expr: Box<dyn Expr>
}

impl Stmt for PrintStmt
{
	fn run(&self, run: &mut VM) -> Result<(), (&'static str, (usize, usize))>
	{ run.visit_printstmt(self) }
}

pub struct VarStmt
{
	pub name: String,
	pub expr: Option<Box<dyn Expr>>
}

impl Stmt for VarStmt
{
	fn run(&self, run: &mut VM) -> Result<(), (&'static str, (usize, usize))>
	{ run.visit_varstmt(self) }
}
